name: Compilation avec GCC

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Recuperation du depot
      uses: actions/checkout@v2

    - name: Configuration de GCC
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Installation de GCC
      run: sudo apt-get install gcc

    - name: Compilation du code C
      run: gcc -o tp2 "TP2 - Circuits/TP2 - Circuits/*.c"